serversTransport:
  insecureSkipVerify: true
entryPoints:
  http:
    address: ':3000'
    http2:
      maxConcurrentStreams: 250
providers:
  file:
    filename: /dynamic/dynamic.yaml

api:
  dashboard: true
ping:
  entryPoint: http
log:
  level: DEBUG
  filePath: /logs/traefik.log
accessLog:
  filePath: /logs/access.log
  fields:
    names:
      StartUTC: drop
